import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { EntriesProvider } from './contexts/entries-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <EntriesProvider>
        {' '}
        <body className='h-screen bg-white p-4'>{children}</body>
      </EntriesProvider>
    </html>
  );
}
