import type { Metadata } from 'next';
import { EntriesProvider } from './contexts/entries-context';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap'
          rel='stylesheet'
        />
      </head>
      <EntriesProvider>
        <body className='h-screen bg-white p-4'>{children}</body>
      </EntriesProvider>
    </html>
  );
}
